CREATE SCHEMA GS;
USE GS;

SHOW SCHEMAS;

CREATE TABLE USERS (
USER_ID INT AUTO_INCREMENT,
NAME VARCHAR(155) NOT NULL,
EMAIL VARCHAR(155) UNIQUE NOT NULL,
PASSWORD VARCHAR(255),
IS_ADMIN BOOLEAN DEFAULT FALSE,
CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY (USER_ID)
);

DESC USERS;
SELECT * FROM USERS;

ALTER TABLE USERS
ADD COLUMN PHONE_NO INT CHECK(PHONE_NO = 10);

ALTER TABLE USERS
DROP COLUMN PHONE_NO;

CREATE TABLE PRODUCTS (
PRODUCT_ID INT AUTO_INCREMENT,
NAME VARCHAR(155) NOT NULL,
DESCRIPTION TEXT,
PRICE DOUBLE(10,2),
IMAGE_URL VARCHAR(255),
IS_AVAILABLE BOOLEAN DEFAULT TRUE,
CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY (PRODUCT_ID)
); 

DESC PRODUCTS;

CREATE TABLE ORDERS (
ORDER_ID INT PRIMARY KEY AUTO_INCREMENT,
USER_ID INT,
STATUS ENUM ("Pending", "Processing", "Shipped", "Delivered", "Cancelled"),
TOTAL_AMOUNT DOUBLE(10,2),
ORDER_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
);

DESC ORDERS;
DROP TABLE ORDERS;

CREATE TABLE ORDER_DETAILS (
ORDER_ITEM_ID INT AUTO_INCREMENT,
ORDER_ID INT,
PRODUCT_ID INT,
QUANTITY INT,
UNIT_PRICE DOUBLE(10,2),
PRIMARY KEY (ORDER_ITEM_ID),
FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID),
FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID)
);

/* ALTER TABLE ORDER_DETAILS
ADD FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID); */
DESC ORDER_DETAILS;

